version: '3'
services:
  app:
    build: ./docker/dev/app
    container_name: trident_app
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/trident:cached
    links:
      - db 
  webserver:
    image: nginx:latest
    container_name: trident_webserver
    ports:
      - "80:80"
    links:
      - app
    volumes:
      - ./app:/var/www/trident:cached
      - ./docker/dev/webserver/trident.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:5.7
    container_name: trident_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: trident
      MYSQL_USER: trident
      MYSQL_PASSWORD: trident